# Generated by Django 2.0.4 on 2018-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=30)),
                ('p_length', models.IntegerField()),
                ('p_mass', models.IntegerField()),
                ('p_accessions', models.CharField(max_length=300)),
                ('p_sequence', models.TextField()),
                ('p_sequence_score', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein2Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_accession', models.CharField(max_length=30)),
                ('d_name', models.CharField(max_length=300)),
                ('protein_id', models.ManyToManyField(to='HomosapProteins.Protein')),
            ],
        ),
    ]
