# Generated by Django 2.0.4 on 2018-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomosapProteins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='p_sequence_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
